<ul>
<li><a href="http://www.scriptol.com/seo/panda-made-simple.php">The Panda patent made simple</a> <span class="rssdate">Mon, 14 Apr 2014 06:25:15 GMT</span><br><span class='rssdesc'>Simplified description of the patent 8,682,892 for ranking pages, images and other resources, assumed penalizing poor quality sites, mainly content farms.</span></li>
<li><a href="http://www.scriptol.com/programming/typescript.php">TypeScript: transition language to the future JavaScript</a> <span class="rssdate">Fri, 11 Apr 2014 16:38:38 GMT</span><br><span class='rssdesc'>This new language from Microsoft brings main features of ECMAScript 6 and 7, without waiting for their implementation in browsers.</span></li>
<li><a href="http://www.scriptol.com/programming/csharp.php">C#, the Java of Microsoft</a> <span class="rssdate">Thu, 10 Apr 2014 09:41:26 GMT</span><br><span class='rssdesc'> The C# language is easier to use than C , however, it require the runtime of .NET to run programs. You can convert you C code with no difficulty. C# was designed by Microsoft (tm) for its new .</span></li>
<li><a href="http://www.scriptol.com/seo/panda-update.php">Understanding the Panda algorithm</a> <span class="rssdate">Wed, 09 Apr 2014 15:21:21 GMT</span><br><span class='rssdesc'>The change in the Google ranking, called Panda from the name of an engineer, impacted 11.8% of US website with poor content, not original or not very useful.</span></li>
<li><a href="http://www.scriptol.com/scripts/advanced-explorer-vs-explorer.php">Advanced Explorer vs Windows Explorer</a> <span class="rssdate">Tue, 17 Dec 2013 13:29:24 GMT</span><br><span class='rssdesc'>From version to version, Windows and its explorer retain the same defects, as a precious heritage.</span></li>
<li><a href="http://www.scriptol.com/html5/canvas/logo.php">Online logo editor in HTML 5 Canvas - By Scriptol.com</a> <span class="rssdate">Sat, 07 Jul 2012 10:53:40 GMT</span><br><span class='rssdesc'> Text offset Shadow </span></li>
<li><a href="http://www.scriptol.com/html5/progress.php">Progress bar in HTML 5 and the HTML 4 equivalent</a> <span class="rssdate">Sat, 07 Jul 2012 10:53:26 GMT</span><br><span class='rssdesc'>The HTML 5 Syntax: The closing tag is mandatory. This tag to see if the browser supports HTML 5. Nothing is displayed unless, but the contents of the tag.</span></li>
<li><a href="http://www.scriptol.com/javascript/nodejs.php">Node.js, a new ecosystem based on JavaScript</a> <span class="rssdate">Sat, 07 Jul 2012 10:53:02 GMT</span><br><span class='rssdesc'>This is a server written in JavaScript, but it could be much more than that.</span></li>
<li><a href="http://www.scriptol.com/programming/quotes.php">Quotes about programming languages</a> <span class="rssdate">Sat, 07 Jul 2012 10:52:45 GMT</span><br><span class='rssdesc'>What computer scientists, authors and programmers think of popular programming languages. All languages Algol 60 (Then taken in C) "I couldn't resist the temptation to put in a null reference, simply because it was so easy to implement.</span></li>
<li><a href="http://www.scriptol.com/xml/svg-applications.php">What can we do with SVG?</a> <span class="rssdate">Sat, 07 Jul 2012 10:51:40 GMT</span><br><span class='rssdesc'>Best current applications achieved with SVG will show you what can be done with this standard graphical language.</span></li>
<li><a href="http://www.scriptol.com/mobile/native-vs-html5.php">Mobile programming: Native vs. HTML 5 vs. Titanium</a> <span class="rssdate">Sat, 07 Jul 2012 10:51:28 GMT</span><br><span class='rssdesc'>Which platform to choose? The advantages and disadvantages when considering all aspects of development.</span></li>
<li><a href="http://www.scriptol.com/programming/graphic-algorithms.php">Amazing algorithms to enhance or transform images</a> <span class="rssdate">Wed, 16 Nov 2011 07:22:15 GMT</span><br><span class='rssdesc'>List of algorithms for image processing whose level of intelligence avoids infinitely complex tasks.</span></li>
<li><a href="http://www.scriptol.com/software/internet-explorer-10.php">Internet Explorer 10</a> <span class="rssdate">Fri, 15 Apr 2011 07:55:29 UTC</span><br><span class='rssdesc'>With Internet Explorer 10, Microsoft wants to develop further support for HTML 5 and CSS 3. A trial version is already available. The shadows are now supported to create widgets similar to the native components of mobile phone systems.</span></li>
<li><a href="http://www.scriptol.com/web/search-engine-future.php">Future of search engines</a> <span class="rssdate">Thu, 07 Apr 11 04:01:19 -0500</span><br><span class='rssdesc'>For Stefan Weitz, who is leading Bing search engine:<em></span></li>
<li><a href="http://www.scriptol.com/technologies/future-computer.php">The computer of tomorrow</a> <span class="rssdate">Sat, 02 Apr 11 12:05:57 -0500</span><br><span class='rssdesc'>You already hold it in the hand, its power will multiply and placed in a dock, it can connect to all devices.For most users, especially those of the Internet, the increasing power of mobile units is becoming sufficient to render the PC useless</span></li>
</ul>

